PATH_TO_PROJECT:=../..
include $(PATH_TO_PROJECT)/.config.mk

include $(PATH_TO_GOAVELTEMK)/makefiles/dbmigrations/base.mk
include $(PATH_TO_GOAVELTEMK)/makefiles/dbmigrations/setup.mk
include $(PATH_TO_GOAVELTEMK)/makefiles/dbmigrations/children.mk
