# PATH_TO_PROJECT が各Makefile で設定されている前提
PATH_TO_SERVERS?=$(PATH_TO_PROJECT)/servers
PATH_TO_APISVR?=$(PATH_TO_SERVERS)/apisvr
PATH_TO_APPLIB?=$(PATH_TO_SERVERS)/applib
PATH_TO_BIZ?=$(PATH_TO_SERVERS)/biz
PATH_TO_SERVER_CONTAINERS?=$(PATH_TO_SERVERS)/containers
PATH_TO_FB_EMU?=$(PATH_TO_SERVER_CONTAINERS)/firebase-emulators
PATH_TO_MYSQL?=$(PATH_TO_SERVER_CONTAINERS)/mysql
PATH_TO_LOCALDEV?=$(PATH_TO_SERVER_CONTAINERS)/localdev
PATH_TO_LOCALTEST?=$(PATH_TO_SERVER_CONTAINERS)/localtest
PATH_TO_DBMIGRATIONS?=$(PATH_TO_SERVERS)/dbmigrations
PATH_TO_SERVER_REPLACEMENTS?=$(PATH_TO_SERVERS)/replacements

PATH_TO_CLIENTS?=$(PATH_TO_PROJECT)/clients
PATH_TO_UISVR?=$(PATH_TO_CLIENTS)/uisvr
PATH_TO_TEST_INTEGRATION?=$(PATH_TO_UISVR)/tests/integration
PATH_TO_TEST_INTEGRATION_CONTAINERS?=$(PATH_TO_TEST_INTEGRATION)/containers

PATH_TO_SWAGGERUI?=$(PATH_TO_PROJECT)/tools/swaggerui
